export const substancias = [
	"Adesivo",
	"Atacador (cadarço)",
	"Bolsa",
	"Calçado finalizado",
	"Componentes metálicos (fivela, ilhós, passador, rebite, pino, alma de aço, biqueira, entre outros)",
	"Couraça e contraforte",
	"Couro",
	"Elástico",
	"Espuma",
	"Fachete",
	"Fecho de contato (Velcro)",
	"Fecho ecler (zíper)",
	"Fita de reforço",
	"Forro",
	"Laminado Sintético",
	"Linha",
	"Palmilha",
	"Salto e tacão",
	"Solado",
	"Tecido e não-tecido",
];
